# ##############################################################################
##  @brief  This pod contains an Ubuntu to be able to test things in the
##          cluster.
##
##  @note   This version is `apt`-capable ! :-)
##
##  @see  https://downey.io/notes/dev/ubuntu-sleep-pod-yaml/
# ##############################################################################
apiVersion: v1
kind:       Pod
metadata:
  namespace:    demo-ubuntu
  name:         ubuntu
  labels:
    app:        ubuntu
spec:
  restartPolicy:    Always
  containers:
  - name:       ubuntu
    image:      ubuntu
    imagePullPolicy:    IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "apt update && export DEBIAN_FRONTEND=noninteractive; apt install -yq curl dnsutils iputils-ping ldap-utils nmap; echo hello; tail -F /dev/null"]
            #      - "apt update && apt install curl -y;"
            #  - "sleep"
            #  - "604800"
