##  @see    https://github.com/paulbouwer/hello-kubernetes

apiVersion: v1
kind:       Service
metadata:
  name:     backend-hello-kubernetes
spec:
  type:     LoadBalancer
  ports:
  - port:       80
    targetPort: 8080
  selector:
    app:        backend-hello-kubernetes
