##  @see    https://github.com/paulbouwer/hello-kubernetes

apiVersion: apps/v1
kind:       Deployment
metadata:
  name:     backend-hello-kubernetes
spec:
  replicas: 2


  selector:
    matchLabels:
      app:  backend-hello-kubernetes


  template:
    metadata:
      labels:
        app:    backend-hello-kubernetes

    spec:
      containers:
      - name:   hello-kubernetes
        image:  paulbouwer/hello-kubernetes:1.8
        ports:
        - containerPort: 8080
