apiVersion: v1
kind:       Pod
metadata:
  namespace:    demo-proxy
  name:         ssl-certs-generation
  labels:
    app:        ssl-certs-generation

spec:
  restartPolicy:    Never

  volumes:
    - name:         certs
      persistentVolumeClaim:
        claimName:  ssl-certs-pvc-certs

  containers:
  - name:           omgwtfssl
    image:          paulczar/omgwtfssl
    volumeMounts:
    - mountPath:    /certs
      name:         certs
    env:
    - name:         SSL_SUBJECT
      value:        proxy.demo.local #<my-server-name>
    - name:         CA_SUBJECT
      value:        webmaster@example.com
    - name:         SSL_KEY
      value:        /certs/local.demo.proxy.key
    - name:         SSL_CSR
      value:        /certs/local.demo.proxy.csr
    - name:         SSL_CERT
      value:        /certs/local.demo.proxy.crt
    
    terminationMessagePath:     /dev/termination-log
    terminationMessagePolicy:   File
