apiVersion: apps/v1
kind:       DaemonSet
metadata:
  name:     traefik-ingress-controller 
  labels:
    k8s-app:    traefik-ingress-lb
    kubernetes.io/cluster-service: "true"

spec:
  selector:
    matchLabels:
      k8s-app:  traefik-ingress-lb

  template:
    metadata:
      labels:
        k8s-app:    traefik-ingress-lb
        name:       traefik-ingress-lb
    spec:
      hostNetwork:  true
      dnsPolicy:    ClusterFirstWithHostNet
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      tolerations:
      - key:        node-role.kubernetes.io/master
        effect:     NoSchedule

      volumes:
      - name: cert
        persistentVolumeClaim:
          claimName:  traefik-certs-pvc-certs

      containers:
      - name:   traefik-ingress-lb
        image:  traefik:v2.1.1
        imagePullPolicy:    Always
        resources:
          requests:
            cpu:    100m
            memory: 20Mi
        volumeMounts:
        - name:             cert
          mountPath:        "/cert/"

        args:
        - --providers.kubernetescrd
        - --entrypoints.web.address=:80
        - --entrypoints.websecure.address=:443
        - --api.insecure
        - --certificatesresolvers.le.acme.email=masuperadresse@monmail.com
        - --certificatesresolvers.le.acme.storage=/cert/acme.json
        - --certificatesResolvers.le.acme.httpChallenge.entryPoint=web
