apiVersion: v1
kind:       Service

metadata:
  name:     traefik-svc

spec:
  selector:
    k8s-app:    traefik-ingress-lb
    app:        traefik-ingress-lb

  ports:
  - name:       web
    port:       80
    targetPort: 80
    
  - name:       websecure
    port:       443
    targetPort: 443
    
  - name:       api
    port:       8080
    targetPort: 8080
