##  @brief  This PVC provides access to a volume containing SSL certs generated
##          by the omgwtfssl pod.

kind:       PersistentVolumeClaim
apiVersion: v1

metadata:

    namespace:  demo-proxy
    name:       ssl-certs-pvc-certs

    #labels:
    #  app: federation-prometheus-server


spec:

    #storageClassName:   ssl-certs

    accessModes:
      - ReadWriteMany # The volume can be mounted read-write by many nodes

    resources:
        requests:
            storage:    1M

